#
# Copyright (c) 2023 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
"""suit-generator module to create and parse SUIT envelopes.

Version of suit-generator follows PEP-440 https://peps.python.org/pep-0440/:
    N(.N)*[{a|b|rc}N][.postN][.devN]

    Where following segments are present:
     - Release segment: N(.N)*
     - Pre-release segment: {a|b|rc}N
     - Post-release segment: .postN
     - Development release segment: .devN

    Example versions:
     1.1.a12 - 1.1.12 alpha release
     1.1.b13 - 1.1.13 beta release
     1.1.rc1 - 1.1 first release candidate
     1.1.dev1 - 1.1 first development release
     1.1.0 - final release

    Version of tool is autogenerated using setuptools_scm. To create new version just add git tag v.X.Y.Z
"""
