version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    level: DEBUG
    filename: suit-generator.log
    mode: a
    backupCount: 10  # max 10 files
    maxBytes: 10485760  # max ten mega bytes (1024*1024*10)
loggers:
  suit_generator.suit.types.common:
    level: DEBUG
    handlers: [file]
  suit_generator.logger:
    level: DEBUG
    handlers: [file]
  ncs:
    level: DEBUG
    handler: [file]
root:
  level: DEBUG
  handlers: [file, console]