name: "Check User Write Access"

on: [push, pull_request]

jobs:
  check-write-access:
    runs-on: ubuntu-latest

    steps:
      - name: "Check if user has write access"
        uses: "lannonbr/repo-permission-check-action@2.0.2"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}